# SPDX-FileCopyrightText: 2026 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: senpai

[project]
name = "senpai"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "torch",
    "torch_geometric",
    "einops",
    "timm",
    "PyYAML",
    "rich",
    "python-dotenv",
    "simple-parsing",
    "wandb",
    "weave",
    "tqdm",
    "matplotlib",
    "pandas>=2.3.3",
]

[tool.setuptools.packages.find]
exclude = ["k8s*", "tests*"]

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyter",
]
