#!/usr/bin/env python3
"""Configure and validate live credentials for the runnable workshop.

This script intentionally avoids third-party dependencies except for the
project's existing `wandb` package during W&B validation.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import stat
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


WORKSHOP_ROOT = Path(__file__).resolve().parent
ENV_PATH = WORKSHOP_ROOT / ".env"

REQUIRED_KEYS = [
    "ANTHROPIC_API_KEY",
    "GITHUB_TOKEN",
    "WANDB_API_KEY",
    "WANDB_ENTITY",
    "WANDB_PROJECT",
    "TARGET_REPO_URL",
    "TARGET_REPO_BRANCH",
    "ADVISOR_BRANCH",
]
OPTIONAL_KEYS = ["EXA_API_KEY", "ANTHROPIC_MODEL"]
DEFAULTS = {
    "ANTHROPIC_MODEL": "claude-3-5-haiku-latest",
    "TARGET_REPO_BRANCH": "main",
    "ADVISOR_BRANCH": "workshop-r1",
}


def read_env_file(path: Path = ENV_PATH) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def merged_values() -> dict[str, str]:
    values = {**DEFAULTS, **read_env_file()}
    for key in REQUIRED_KEYS + OPTIONAL_KEYS:
        if os.environ.get(key):
            values[key] = os.environ[key]
    return values


def prompt_value(key: str, current: str = "") -> str:
    label = f"{key}"
    if current:
        label += f" [{redact(current)}]"
    label += ": "
    if "KEY" in key or "TOKEN" in key:
        value = getpass.getpass(label)
    else:
        value = input(label)
    return value.strip() or current


def redact(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "<set>"
    return f"{value[:4]}...{value[-4:]}"


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by workshop/setup_credentials.py",
        "# Do not commit this file.",
        "",
    ]
    for key in REQUIRED_KEYS + OPTIONAL_KEYS:
        if key in values:
            lines.append(f"{key}={values[key]}")
    ENV_PATH.write_text("\n".join(lines) + "\n")
    ENV_PATH.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"Wrote {ENV_PATH} with 0600 permissions.")


def github_slug(repo_url: str) -> str:
    parsed = urllib.parse.urlparse(repo_url)
    if parsed.netloc == "github.com":
        slug = parsed.path.strip("/")
    else:
        slug = repo_url.split("github.com", 1)[-1].lstrip(":/")
    return slug.removesuffix(".git")


def http_json(req: urllib.request.Request, timeout: int = 20) -> dict:
    with urllib.request.urlopen(req, timeout=timeout) as response:
        body = response.read()
    return json.loads(body or b"{}")


def validate_anthropic(values: dict[str, str]) -> None:
    payload = {
        "model": values.get("ANTHROPIC_MODEL", DEFAULTS["ANTHROPIC_MODEL"]),
        "max_tokens": 8,
        "messages": [{"role": "user", "content": "Reply with OK."}],
    }
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=json.dumps(payload).encode(),
        method="POST",
        headers={
            "x-api-key": values["ANTHROPIC_API_KEY"],
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
    )
    http_json(req)
    print("Anthropic: OK")


def validate_github(values: dict[str, str]) -> None:
    slug = github_slug(values["TARGET_REPO_URL"])
    branch = values["TARGET_REPO_BRANCH"]
    for path, label in [
        (f"/repos/{slug}", f"repo {slug}"),
        (f"/repos/{slug}/branches/{urllib.parse.quote(branch, safe='')}", f"branch {branch}"),
    ]:
        req = urllib.request.Request(
            f"https://api.github.com{path}",
            headers={
                "authorization": f"Bearer {values['GITHUB_TOKEN']}",
                "accept": "application/vnd.github+json",
                "user-agent": "senpai-workshop-setup",
            },
        )
        http_json(req)
        print(f"GitHub {label}: OK")


def validate_wandb(values: dict[str, str]) -> None:
    os.environ["WANDB_API_KEY"] = values["WANDB_API_KEY"]
    import wandb

    api = wandb.Api()
    path = f"{values['WANDB_ENTITY']}/{values['WANDB_PROJECT']}"
    # Fetching the project object validates access without enumerating runs.
    api.project(values["WANDB_PROJECT"], entity=values["WANDB_ENTITY"])
    print(f"W&B {path}: OK")


def validate_all(values: dict[str, str]) -> int:
    checks = [
        ("Anthropic", validate_anthropic),
        ("GitHub", validate_github),
        ("W&B", validate_wandb),
    ]
    failures = 0
    for label, fn in checks:
        try:
            fn(values)
        except (urllib.error.HTTPError, urllib.error.URLError, KeyError, Exception) as exc:
            failures += 1
            print(f"{label}: FAILED ({type(exc).__name__}: {exc})", file=sys.stderr)
    return failures


def print_commands() -> None:
    print("\nRun notebooks with:")
    print("  uv run python workshop/notebooks/00_environment_check.py")
    print("  uv run python workshop/notebooks/01_llm_calls_to_hypotheses.py")
    print("  uv run python workshop/notebooks/02_tool_calls_and_contracts.py")
    print("  uv run python workshop/notebooks/03_single_agent_student_loop.py")
    print("  uv run python workshop/notebooks/04_multiagent_advisor_student_flow.py")
    print("  uv run python workshop/notebooks/05_wandb_and_weave_as_memory.py")
    print("  uv run python workshop/notebooks/06_k8s_autoresearch_dry_run.py")
    print("  uv run python workshop/notebooks/07_physical_ai_claim_review.py")
    print("  uv run python workshop/notebooks/08_full_autoresearch_trace.py")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-only", action="store_true", help="Validate existing env/.env values without prompting or writing.")
    parser.add_argument("--no-validate", action="store_true", help="Write credentials but skip live service validation.")
    args = parser.parse_args()

    values = merged_values()
    if args.check_only:
        missing = [key for key in REQUIRED_KEYS if not values.get(key)]
        if missing:
            print(f"Missing required values: {', '.join(missing)}", file=sys.stderr)
            return 2
    else:
        print("Enter workshop credentials. Existing values are shown redacted.")
        for key in REQUIRED_KEYS:
            values[key] = prompt_value(key, values.get(key, ""))
        for key in OPTIONAL_KEYS:
            values[key] = prompt_value(key, values.get(key, DEFAULTS.get(key, "")))
        missing = [key for key in REQUIRED_KEYS if not values.get(key)]
        if missing:
            print(f"Missing required values: {', '.join(missing)}", file=sys.stderr)
            return 2
        write_env(values)

    if not args.no_validate:
        failures = validate_all(values)
        if failures:
            print(f"{failures} validation check(s) failed.", file=sys.stderr)
            return 1

    print_commands()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
